### PR TITLE
Configure jekyll-feed to write atom.xml

### PR DESCRIPTION
**Pull request by kemitchell**
@joshka, will this due for you? Sample `atom.xml` with full content:

https://gist.github.com/70f87df932c563d259c3dcae9a4591f5

This would serve at https://writing.kemitchell.com/atom.xml

### CODE REVIEW

**Comment by kemitchell** [comment]
Would close #6.

**Comment by joshka** [comment]
This will do the trick I think (not an expert on this). In https://github.com/kemitchell/writing/blob/master/_includes/top.html, you'll need to also add:
`<link type="application/atom+xml" rel="alternate" href="https://writing.kemitchell.com/atom.xml">`.

**Comment by kemitchell** [comment]
Deployed. https://writing.kemitchell.com/atom.xml

**Comment by kemitchell** [comment]
Thanks again, @joshka. Wouldn't have happened without you reaching out.

**Comment by joshka** [comment]
image
Thanks :)

**Comment by kemitchell** [comment]
@joshka Cool!

**Pull request merged**
